const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");
const logger = require("../utils/logger");

const generateChallan = (session, operator) => {
  return new Promise((resolve, reject) => {
    try {
      const reportsDir = path.resolve(process.env.REPORTS_DIR || "../data/reports");
      if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

      const fileName = `challan-${session._id}-${Date.now()}.pdf`;
      const filePath = path.join(reportsDir, fileName);

      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // ── Header ──────────────────────────────────────────
      doc
        .fillColor("#1F4E79")
        .fontSize(24)
        .font("Helvetica-Bold")
        .text("AgniSight-AI", { align: "center" });

      doc
        .fillColor("#2E75B6")
        .fontSize(13)
        .font("Helvetica")
        .text("Warehouse Packing Challan", { align: "center" });

      doc.moveDown(0.5);
      doc
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .strokeColor("#2E75B6")
        .lineWidth(2)
        .stroke();
      doc.moveDown(1);

      // ── Session Details ──────────────────────────────────
      doc
        .fillColor("#1F4E79")
        .fontSize(13)
        .font("Helvetica-Bold")
        .text("Packing Session Details");
      doc.moveDown(0.5);

      const rows = [
        ["Batch ID",        session.batchId],
        ["Session ID",      session._id.toString()],
        ["Operator Name",   operator.name],
        ["Operator Email",  operator.email],
        ["Status",          session.status.toUpperCase()],
        ["Started At",      new Date(session.startedAt).toLocaleString()],
        ["Ended At",        session.endedAt ? new Date(session.endedAt).toLocaleString() : "—"],
        ["Final Box Count", session.finalBoxCount.toString()],
        ["Total Frames",    session.totalFrames.toString()],
        ["Average FPS",     session.avgFps.toString()],
        ["YOLO Conf.",      session.yoloConfThreshold.toString()],
        ["YOLO IOU",        session.yoloIouThreshold.toString()],
      ];

      rows.forEach(([label, value], i) => {
        const bg = i % 2 === 0 ? "#F0F7FF" : "#FFFFFF";
        const rowY = doc.y;

        doc
          .rect(50, rowY, 495, 22)
          .fillColor(bg)
          .fill();

        doc
          .fillColor("#1F4E79")
          .fontSize(10)
          .font("Helvetica-Bold")
          .text(label, 60, rowY + 6, { width: 160 });

        doc
          .fillColor("#1A1A1A")
          .font("Helvetica")
          .text(value, 230, rowY + 6, { width: 300 });

        doc.moveDown(0.6);
      });

      doc.moveDown(1);

      // ── Video Reference ──────────────────────────────────
      if (session.outputVideoPath || session.videoPath) {
        doc
          .moveTo(50, doc.y)
          .lineTo(545, doc.y)
          .strokeColor("#CCCCCC")
          .lineWidth(1)
          .stroke();
        doc.moveDown(0.5);

        doc
          .fillColor("#1F4E79")
          .fontSize(11)
          .font("Helvetica-Bold")
          .text("Video Reference");
        doc.moveDown(0.3);

        doc
          .fillColor("#595959")
          .fontSize(9)
          .font("Helvetica")
          .text(session.outputVideoPath || session.videoPath);
        doc.moveDown(1);
      }

      // ── Footer ───────────────────────────────────────────
      doc
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .strokeColor("#2E75B6")
        .lineWidth(2)
        .stroke();
      doc.moveDown(0.5);

      doc
        .fillColor("#595959")
        .fontSize(9)
        .font("Helvetica")
        .text(
          `Generated by AgniSight-AI  •  ${new Date().toLocaleString()}  •  Confidential`,
          { align: "center" }
        );

      doc.end();

      stream.on("finish", () => {
        logger.info(`Challan generated: ${filePath}`);
        resolve(filePath);
      });

      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateChallan };